- name: 文件操作
  file:
    path: 文件地址
    owner: 属主 | null
    group: 属组 | null
    mode: 权限 | '0644'
    state: 状态 | file

- name: 软链接操作
  file:
    src: 原地址
    dest: 目标地址
    owner: 属主 | null
    group: 属组 | null
    state: 状态 | link

- name: 目录操作
  file:
    path: 目录地址
    state: 状态 | directory
    recurse: 是否递归 | yes
    owner: 属主 | null
    group: 属组 | null
    mode: 权限 | '0755'